sonar.projectKey=ArcGIS-JS
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.exclusions=node_modules/**,dist/**,build/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/*.test.jsx,**/__mocks__/**,**/setupTests.js,src/main.jsx,src/config/ArcGISConfiguration.js
sonar.tests=src,test
sonar.test.inclusions=**/*.test.js,**/*.test.jsx